### ISSUE TITLE
Modul 1.2 Assigement

### ISSUE THREAD

**Issue by Larixxa** [Campus-Advisors/campus-advisor-training-rlangbehn#24]
Larissa@LAPTOP-PR3QRL52 MINGW64 ~ (master)
$ mkdir MyProject

Larissa@LAPTOP-PR3QRL52 MINGW64 ~ (master)
$ cd MyProject

Larissa@LAPTOP-PR3QRL52 MINGW64 ~/MyProject (master)
$ ls

Larissa@LAPTOP-PR3QRL52 MINGW64 ~/MyProject (master)
$ git init
Initialized empty Git repository in C:/Users/larix/MyProject/.git/
Larissa@LAPTOP-PR3QRL52 MINGW64 ~/MyProject (master)
$ ls

Larissa@LAPTOP-PR3QRL52 MINGW64 ~/MyProject (master)
$ ls -a
./  ../  .git/

Larissa@LAPTOP-PR3QRL52 MINGW64 ~/MyProject (master)
$ cd .git

Larissa@LAPTOP-PR3QRL52 MINGW64 ~/MyProject/.git (GIT_DIR!)
$ ls
config  description  HEAD  hooks/  info/  objects/  refs/

Larissa@LAPTOP-PR3QRL52 MINGW64 ~/MyProject/.git (GIT_DIR!)
$ cd ..

Larissa@LAPTOP-PR3QRL52 MINGW64 ~/MyProject (master)
$ touch README.md

Larissa@LAPTOP-PR3QRL52 MINGW64 ~/MyProject (master)
$ ls
README.md
Larissa@LAPTOP-PR3QRL52 MINGW64 ~/MyProject (master)
$ git status
On branch master

No commits yet

Untracked files:
  (use "git add <file>..." to include in what will be committed)
        README.md

nothing added to commit but untracked files present (use "git add" to track)

Larissa@LAPTOP-PR3QRL52 MINGW64 ~/MyProject (master)
$ git add README.md
Larissa@LAPTOP-PR3QRL52 MINGW64 ~/MyProject (master)
$ git status
On branch master

No commits yet

Larissa@LAPTOP-PR3QRL52 MINGW64 ~/MyProject (master)
$ git status
On branch master
nothing to commit, working tree clean

Larissa@LAPTOP-PR3QRL52 MINGW64 ~/MyProject (master)
$ git log
commit 217ea81f9be7ccd69ed1547ac356c9cbb09d0798 (HEAD -> master)
Author: FirstName LastName <l.sowada@studnets.rak.de>
Date:   Wed May 13 13:37:53 2020 +0200

    Add README.md

**Comment by rlangbehn** [comment]
Though I can not find your git commit command sequence from your git log output I can see that you solved this assignment. Well done!
